// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fast_api.EntityFramework;

namespace fast_api.Migrations
{
    [DbContext(typeof(FastContext))]
    [Migration("20200501231518_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("fast_api.EntityFramework.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Buy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Sell")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("fast_api.EntityFramework.SelectionContainer", b =>
                {
                    b.Property<int>("SelectionContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Buy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Sell")
                        .HasColumnType("int");

                    b.HasKey("SelectionContainerId");

                    b.ToTable("SelectionContainers");
                });

            modelBuilder.Entity("fast_api.EntityFramework.SelectionContainerItem", b =>
                {
                    b.Property<int>("SelectionContainerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<bool>("Guaranteed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SelectionContainerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("SelectionContainerItems");
                });

            modelBuilder.Entity("fast_api.EntityFramework.SelectionContainerItem", b =>
                {
                    b.HasOne("fast_api.EntityFramework.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fast_api.EntityFramework.SelectionContainer", "SelectionContainer")
                        .WithMany("SelectionContainerItems")
                        .HasForeignKey("SelectionContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
